import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { NarrationService, validateSelection } from '../src/server/narration.ts';
import { createAudioServer } from '../src/server/app.ts';
import { MODEL } from '../src/audio/types.ts';

const mp3 = Buffer.concat([Buffer.from('ID3'), Buffer.alloc(50)]);
test('OpenAI selection sends only its key and voice to the direct endpoint; Fish remains isolated', async t => {
  const directory = await mkdtemp(join(tmpdir(), 'bookworm-providers-'));
  t.after(() => rm(directory, { recursive: true }));
  const calls: { url: string; auth: string | null; body: object }[] = [];
  const service = await NarrationService.open(directory, { openrouter: 'router-secret', openai: 'openai-secret' }, async function(this: unknown, url, init) {
    assert.equal(this, undefined, 'native fetch must not receive the provider as its receiver');
    calls.push({ url: String(url), auth: new Headers(init?.headers).get('authorization'), body: JSON.parse(String(init?.body)) });
    return new Response(mp3, { headers: { 'Content-Type': 'audio/mpeg' } });
  });
  const fishProfile = service.profile.id;
  await service.synthesize('Hello.', new AbortController().signal);
  assert.deepEqual(calls[0], { url: 'https://openrouter.ai/api/v1/audio/speech', auth: 'Bearer router-secret', body: { model: MODEL, input: 'Hello.', response_format: 'mp3' } });
  await service.select({ provider: 'openai', voice: 'cedar' });
  assert.notEqual(service.profile.id, fishProfile);
  await service.synthesize('Hello.', new AbortController().signal);
  assert.deepEqual(calls[1], { url: 'https://api.openai.com/v1/audio/speech', auth: 'Bearer openai-secret', body: { model: 'gpt-4o-mini-tts', voice: 'cedar', input: 'Hello.', response_format: 'mp3' } });
  const cedarProfile = service.profile.id;
  await service.select({ provider: 'openai', voice: 'marin' });
  assert.notEqual(service.profile.id, cedarProfile);
  assert(!JSON.stringify(service.settings()).includes('secret'));
  const reopened = await NarrationService.open(directory, { openrouter: 'router-secret', openai: 'openai-secret' });
  assert.deepEqual(reopened.settings().selection, { provider: 'openai', voice: 'marin' });
});
test('keys save and remove independently; missing OpenAI key never falls back to funded Fish', async t => {
  const directory = await mkdtemp(join(tmpdir(), 'bookworm-providers-'));
  t.after(() => rm(directory, { recursive: true }));
  let calls = 0;
  const service = await NarrationService.open(directory, { openrouter: 'router-secret' }, async () => { calls++; return new Response(mp3); });
  await service.select({ provider: 'openai', voice: 'marin' });
  await assert.rejects(service.synthesize('Hello.', new AbortController().signal), /OpenAI API key/);
  assert.equal(calls, 0);
  await service.updateKey('saved-openai-key', 'openai');
  assert.equal(service.configured, true);
  await service.updateKey('', 'openai');
  const reopened = await NarrationService.open(directory, { openrouter: 'router-secret', openai: 'environment-openai-key' });
  assert.deepEqual(reopened.settings().keys, { openrouter: true, openai: false });
  await reopened.select({ provider: 'openrouter', voice: '' });
  assert.equal(reopened.configured, true);
  for (const invalid of [{ provider: 'other', voice: 'marin' }, { provider: 'openai', voice: 'invented' }, { provider: 'openrouter', voice: 'marin' }, null]) assert.throws(() => validateSelection(invalid));
});
test('HTTP selection validates voices and rejects stale speech profiles after switching', async t => {
  const directory = await mkdtemp(join(tmpdir(), 'bookworm-selection-'));
  const service = await NarrationService.open(directory);
  const server = createAudioServer(service, '/tmp/no-public-files', (key, provider) => service.updateKey(key, provider), { read: () => service.settings(), select: selection => service.select(selection) });
  await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(async () => { await new Promise<void>(resolve => server.close(() => resolve())); await rm(directory, { recursive: true }); });
  const address = server.address(); assert(address && typeof address !== 'string');
  const origin = `http://127.0.0.1:${address.port}`;
  const headers = { 'Content-Type': 'application/json', 'X-Bookworm-Client': 'audio-v1' };
  const oldProfile = service.profile.id;
  const request = (path: string, body: object) => fetch(origin + path, { method: 'PUT', headers, body: JSON.stringify(body) });
  assert.equal((await request('/api/audio/selection', { provider: 'openai', voice: 'bad' })).status, 400);
  assert.equal((await request('/api/audio/selection', { provider: 'openai', voice: 'nova' })).status, 200);
  assert.equal((await request('/api/audio/key', { provider: 'other', apiKey: 'x'.repeat(25) })).status, 400);
  assert.equal((await request('/api/audio/key', { provider: 'openai', apiKey: 'x'.repeat(25) })).status, 200);
  const config = await fetch(origin + '/api/audio/config').then(r => r.json());
  assert.deepEqual(config.keys, { openrouter: false, openai: true });
  assert.equal(config.profile.voice, 'nova');
  assert(!JSON.stringify(config).includes('x'.repeat(25)));
  const stale = await fetch(origin + '/api/audio/speech', { method: 'POST', headers, body: JSON.stringify({ text: 'Hello.', profileId: oldProfile }) });
  assert.equal(stale.status, 409);
});
