import { mountCatalog, bookFromPlainText } from '../books/gutenberg.ts';
import { mountRecommendations } from '../books/recommendations.ts';
export function mountSimpleReader(audio) {
'use strict';
const $=s=>document.querySelector(s), icon=name=>`<svg aria-hidden="true"><use href="#i-${name}"/></svg>`;
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='bookworm-simple-audio-v1';
const samples=[
{id:'alice',title:'Alice in Wonderland',author:'Lewis Carroll',style:'',art:'wonder',sample:true,chapters:[{title:'Down the Rabbit-Hole',paragraphs:[{text:'Alice sat beside her sister on the riverbank. The afternoon was warm, and the book her sister was reading had neither pictures nor conversations. Alice wondered what use a book could be without either.'},{text:'Then a white rabbit with pink eyes hurried past. That was unusual, but not nearly as unusual as what happened next: the Rabbit took a watch out of its waistcoat pocket, checked the time, and rushed on.'},{text:'Alice was on her feet in an instant. A rabbit with a pocket, and a watch to take out of it! She followed it across the field, just in time to see it disappear down a large rabbit-hole under the hedge.'},{text:'A moment later, Alice followed. She did not stop to consider how she would get out again. The tunnel ran straight ahead for a little way, and then dipped suddenly down.'}]},{title:'A Hall of Little Doors',paragraphs:[{text:'The fall ended on a heap of sticks and dry leaves. Alice got up, brushed herself off, and found a long passage stretching into the distance. The White Rabbit was still just ahead.'},{text:'She came to a hall lit by a row of lamps. Doors stood all around it, but every one was locked. On a little glass table she found a tiny golden key.'},{text:'At first the key seemed much too small for any of the doors. Then Alice noticed a curtain she had missed before. Behind it was a little door, and beyond that door was the loveliest garden she had ever seen.'}]}]},
{id:'odyssey',title:'The Odyssey',author:'Homer',style:'blue',art:'sea',sample:true,chapters:[{title:'The Long Way Home',paragraphs:[{text:'Beyond the last familiar headland, the sea opened wide. Odysseus stood at the bow and watched the light move across the water. Somewhere beyond that restless horizon was Ithaca.'},{text:'His companions knew the names of distant ports and the moods of changing winds. Yet no one could say how many mornings would pass before they saw their own shore again.'},{text:'For now, the sail was full. The ship creaked, the oars lifted, and the journey continued. Home was a place in the distance, but it was also the thought that kept them moving.'}]},{title:'An Unfamiliar Shore',paragraphs:[{text:'By evening, a dark shape rose from the sea. An island, quiet under the fading sky. The crew brought the ship into a sheltered cove and stepped onto sand still warm from the sun.'},{text:'They needed water and food. They also needed care. Every new shore offered a promise, and every promise carried something they did not yet understand.'}]}]},
{id:'garden',title:'The Secret Garden',author:'Frances Hodgson Burnett',style:'ochre',art:'leaf',sample:true,chapters:[{title:'A Door in the Wall',paragraphs:[{text:'The path bent around an old brick wall. Mary walked slowly, watching a small bird hop from branch to branch. The garden on the other side seemed to be keeping a secret.'},{text:'A gust of wind lifted the ivy. For a moment, she saw the shape of a door beneath the leaves. She drew nearer and placed her hand against the wood.'},{text:'The key turned. Beyond the wall, bare branches reached toward the light, and little green shoots were beginning to push through the earth. The garden had been waiting for spring.'}]}]}
];
let stored;try{stored=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{stored={}}if(!stored||typeof stored!=='object'||Array.isArray(stored))stored={};
const validBook=b=>b&&typeof b.id==='string'&&typeof b.title==='string'&&typeof b.author==='string'&&Array.isArray(b.chapters)&&b.chapters.length>0&&b.chapters.every(c=>typeof c.title==='string'&&Array.isArray(c.paragraphs)&&c.paragraphs.length&&c.paragraphs.every(p=>typeof p.text==='string'&&p.text.trim()));
let imported=Array.isArray(stored.imported)?stored.imported.filter(validBook):[];
let added=Array.isArray(stored.added)?stored.added.filter(id=>samples.some(b=>b.id===id)):[];
let books=[...samples.slice(0,2),...samples.slice(2).filter(b=>added.includes(b.id)),...imported];
let positions=stored.positions&&typeof stored.positions==='object'?stored.positions:{};
let marks=stored.marks&&typeof stored.marks==='object'?stored.marks:{};
let prefs={rate:[.8,1,1.2,1.5,2].includes(Number(stored.rate))?Number(stored.rate):1};
let active=books.find(b=>b.id===stored.active)||books[0],index=0,playing=false,finished=false,toastTimer,storageOkay=true,binding=false;
const compiled=new Map();
function segments(b=active){if(!compiled.has(b.id)){const list=[];b.chapters.forEach((c,ci)=>c.paragraphs.forEach((p,pi)=>audio.split(p.text).forEach((text,part)=>list.push({text,ci,pi,part}))));compiled.set(b.id,list)}return compiled.get(b.id)}
function clamp(n,b=active){return Math.max(0,Math.min(segments(b).length-1,Number.isFinite(Number(n))?Math.floor(Number(n)):0))}
index=clamp(positions[active.id]);
function notify(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4000)}
function persist(){positions[active.id]=index;try{localStorage.setItem(KEY,JSON.stringify({imported,added,positions,marks,active:active.id,...prefs}));storageOkay=true}catch{if(storageOkay)notify('Browser storage is full or unavailable. New changes last only this session.');storageOkay=false}$('#save-status').textContent=storageOkay?'Place saved':'Session only';$('#position-note').textContent=storageOkay?'Your place is saved automatically.':'Storage unavailable. Your place lasts this session only.';return storageOkay}
function cover(b){return `<div class="cover ${['blue','ochre','clay'].includes(b.style)?b.style:''}" aria-hidden="true"><small>The personal library</small><strong>${escapeHTML(b.title)}</strong>${icon(['wonder','sea','leaf'].includes(b.art)?b.art:'book')}<span>${escapeHTML(b.author)}</span></div>`}
function renderLibrary(){$('#companion-start-book').textContent='With '+active.title;const b=active,n=clamp(positions[b.id],b),s=segments(b)[n],pct=Math.round(n/Math.max(1,segments(b).length-1)*100);$('#continue-card').innerHTML=`${cover(b)}<div><div class="eyebrow">${n?'Continue your book':'A good place to begin'}</div><h2>${escapeHTML(b.title)}</h2><p class="muted">${escapeHTML(b.author)}</p><p class="location">Chapter ${s.ci+1} · ${escapeHTML(b.chapters[s.ci].title)}</p><div class="track"><i style="width:${pct}%"></i></div></div><div class="continue-action"><button class="btn primary" data-open="${escapeHTML(b.id)}">${icon('play')}${n?'Continue reading':'Open book'}</button><p>${b.sample?'Adapted sample excerpt':'Your imported book'}</p></div>`;$('#shelf').innerHTML=books.map(b=>`<button class="book-card" data-open="${escapeHTML(b.id)}">${cover(b)}<h3>${escapeHTML(b.title)}</h3><p>${b.sample?'Sample · ':''}${b.chapters.length} chapters</p></button>`).join('')+`<button class="add-card" data-dialog="add-dialog">${icon('plus')}<span>Add your next book</span></button>`;$('#book-count').textContent=`${books.length} books`}
function renderReader(){const s=segments()[index],ch=active.chapters[s.ci];$('#reader-book').textContent=active.title;$('#chapter-title').textContent=ch.title;$('#chapter-meta').textContent=`Chapter ${s.ci+1} of ${active.chapters.length}${active.sample?' · Adapted sample excerpt':''}`;$('#prose').innerHTML=ch.paragraphs.map((p,pi)=>`<p class="${s.pi===pi?'current':''}"><button data-paragraph="${pi}" aria-label="Start at paragraph ${pi+1}">${escapeHTML(p.text)}</button></p>`).join('');$('#next-chapter').disabled=s.ci===active.chapters.length-1;$('#playing-book').textContent=active.title;$('#progress').max=segments().length-1;$('#progress').value=index;$('#progress').setAttribute('aria-valuetext',`Chapter ${s.ci+1}, passage ${index+1} of ${segments().length}`);$('#percent').textContent=Math.round(index/Math.max(1,segments().length-1)*100)+'%';$('#bookmark').setAttribute('aria-pressed',String(marks[active.id]===index));$('#bookmark').style.background=marks[active.id]===index?'var(--light)':'';$('#previous').disabled=index===0;$('#next').disabled=index===segments().length-1;updatePlayer()}
function updatePlayer(){const state=audio.snapshot();$('#play-toggle').innerHTML=icon(playing?'pause':'play');$('#play-toggle').setAttribute('aria-label',playing?'Pause narration':state.error?'Retry narration':finished?'Replay book':'Play narration');$('#play-status').textContent=state.error?'Narration unavailable · retry':state.status==='preparing'?'Preparing narration…':playing?'Listening · AI narration':finished?'Book finished':'Paused · passage '+(index+1);$('#speed').value=String(prefs.rate)}
function stop(){audio.pause()}
function play(){void audio.play()}
function seek(n){audio.seek(clamp(n))}
function bindBook(){binding=true;audio.load(segments().map(s=>({bookId:'simple:'+active.id,chapterId:String(s.ci),passageId:`${s.ci}:${s.pi}:${s.part}`,text:s.text})),index);binding=false;syncAudio(audio.snapshot())}
function syncAudio(state){if(binding)return;const changed=index!==state.index;index=clamp(state.index);playing=['playing','preparing'].includes(state.status);finished=state.status==='ended';if(changed){persist();renderReader()}else updatePlayer()}
function openBook(id){const b=books.find(b=>b.id===id);if(!b)return;stop();active=b;index=clamp(positions[b.id]);finished=false;bindBook();persist();$('#library').hidden=true;$('#reader').hidden=false;$('#player').hidden=false;document.body.classList.add('reading');renderReader();window.scrollTo(0,0);$('#back-library').focus({preventScroll:true})}
function library(){stop();persist();$('#reader').hidden=true;$('#player').hidden=true;$('#library').hidden=false;document.body.classList.remove('reading');renderLibrary();window.scrollTo(0,0)}
function renderChapters(){const s=segments()[index];$('#chapter-list').innerHTML=active.chapters.map((c,i)=>`<button class="chapter-row" data-chapter="${i}" aria-current="${s.ci===i}"><div><span>CHAPTER ${String(i+1).padStart(2,'0')}</span><strong>${escapeHTML(c.title)}</strong></div>${s.ci===i?icon('book'):icon('next')}</button>`).join('');const mark=marks[active.id];$('#bookmark-entry').innerHTML=Number.isInteger(mark)&&mark>=0&&mark<segments().length?`<button class="text-btn" id="return-mark">${icon('mark')}Saved bookmark · chapter ${segments()[mark].ci+1}</button>`:'<p>No bookmark yet. Use the bookmark button to keep a particular passage.</p>'}
function addToLibrary(book){
  if(book.gutenbergId && books.some(existing=>existing.gutenbergId===book.gutenbergId))return;
  imported.push(book);books.push(book);persist();$('#add-dialog').close();library();
  notify(storageOkay?`“${book.title}” is in your library.`:'Added for this session; browser storage is full.');
}
const catalogUI=mountCatalog({escapeHTML,parseEpub:file=>window.parseBookWormAIEPUB(file),isReadable:validBook,shelvedIds:()=>new Set(books.map(b=>b.gutenbergId).filter(Number.isInteger)),addToLibrary});
const recommendationsUI=mountRecommendations({settings:()=>{$('#add-dialog').close();dialog('settings-dialog');$('#exa-key').focus()},shelvedIds:()=>new Set(books.map(b=>b.gutenbergId).filter(Number.isInteger)),shelfBooks:()=>books.filter(b=>!b.sample).map(b=>({title:b.title,author:/^(from your |your )?personal library$/i.test(b.author)?'':b.author})),select:book=>{clearTimeout(catalogTimer);$('#catalog-query').value='';chooseSource('catalog');catalogUI.showRecommendation(book);$('#catalog-tab').focus();}});
function catalog(){catalogUI.render()}
let catalogTimer;
$('#catalog-form').addEventListener('submit',event=>{event.preventDefault();clearTimeout(catalogTimer);void catalogUI.search($('#catalog-query').value)});
$('#catalog-query').addEventListener('input',event=>{const query=event.target.value;clearTimeout(catalogTimer);catalogTimer=setTimeout(()=>catalogUI.search(query),350)});
$('#catalog-pending').addEventListener('change',event=>{const file=event.target.files?.[0];if(file)void catalogUI.importPending(file)});
$('#add-dialog').addEventListener('close',()=>{clearTimeout(catalogTimer);catalogUI.cancelPending();recommendationsUI.cancel()});
function dialog(id){if(playing){stop();persist()}if(id==='chapters-dialog')renderChapters();if(id==='add-dialog'){catalog();catalogUI.reset();$('#import-error').hidden=true;$('#file').value='';if($('#recommend-tab').getAttribute('aria-selected')==='true')void recommendationsUI.refresh()}$('#'+id).showModal()}
function chooseSource(source){
  if(source==='catalog')catalogUI.probe();
  if(source==='recommend')void recommendationsUI.refresh();else recommendationsUI.cancel();
  for(const name of ['device','catalog','recommend'])$('#'+name+'-panel').hidden=name!==source;
  document.querySelectorAll('[data-source]').forEach(b=>{b.setAttribute('aria-selected',String(b.dataset.source===source));b.tabIndex=b.dataset.source===source?0:-1});
}
document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;if(el.dataset.open)openBook(el.dataset.open);if(el.dataset.dialog)dialog(el.dataset.dialog);if(el.hasAttribute('data-close'))el.closest('dialog').close();if(el.dataset.source)chooseSource(el.dataset.source);if(el.dataset.chapter!==undefined){seek(segments().findIndex(s=>s.ci===Number(el.dataset.chapter)));$('#chapters-dialog').close();window.scrollTo(0,0)}if(el.dataset.paragraph!==undefined){const ci=segments()[index].ci;seek(segments().findIndex(s=>s.ci===ci&&s.pi===Number(el.dataset.paragraph)))}if(el.id==='return-mark'){seek(marks[active.id]);$('#chapters-dialog').close()}if(el.dataset.addGutenberg)catalogUI.add(Number(el.dataset.addGutenberg));if(el.dataset.downloadGutenberg)catalogUI.download(Number(el.dataset.downloadGutenberg));if(el.id==='catalog-more')void catalogUI.search($('#catalog-query').value,true);if(el.id==='catalog-cancel')catalogUI.cancelPending();});
$('.tabs').addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const tabs=[...document.querySelectorAll('[data-source]')];const current=tabs.findIndex(t=>t.getAttribute('aria-selected')==='true');const index=e.key==='Home'?0:e.key==='End'?tabs.length-1:(current+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;chooseSource(tabs[index].dataset.source);tabs[index].focus()}});
$('#brand').onclick=library;$('#back-library').onclick=library;$('#play-toggle').onclick=()=>{if(playing){stop();persist()}else play()};$('#previous').onclick=()=>seek(index-1);$('#next').onclick=()=>seek(index+1);$('#progress').oninput=e=>seek(e.target.value);$('#next-chapter').onclick=()=>{seek(segments().findIndex(s=>s.ci===segments()[index].ci+1));window.scrollTo(0,0)};$('#bookmark').onclick=()=>{marks[active.id]=index;persist();renderReader();notify(storageOkay?'Bookmark saved. Find it in Chapters.':'Bookmark kept for this session.')};$('#speed').onchange=e=>{prefs.rate=Number(e.target.value);audio.setRate(prefs.rate);persist();updatePlayer()};
$('#file').onchange=async e=>{const f=e.target.files[0];if(!f)return;$('#import-error').hidden=true;e.target.disabled=true;try{if(f.size>10*1024*1024)throw Error('Please choose a file under 10 MB.');const ext=f.name.split('.').pop().toLowerCase();if(!['epub','txt'].includes(ext))throw Error('Choose an EPUB or plain text file.');let b;if(ext==='epub')b=await window.parseBookWormAIEPUB(f);else{const text=await f.text();if(text.includes('\0'))throw Error('This does not look like a plain text file.');if(text.length>3*1024*1024)throw Error('Please use a shorter text file (under 3 MB of text).');b=bookFromPlainText(text,f.name.replace(/\.txt$/i,''),'Your personal library')}if(!validBook(b))throw Error('No readable text was found.');b.style='clay';b.art='book';b.sample=false;addToLibrary(b)}catch(err){$('#import-error').textContent=err.message||'This file could not be opened.';$('#import-error').hidden=false}finally{e.target.disabled=false;e.target.value=''}};
window.addEventListener('pagehide',()=>{persist();stop()});document.addEventListener('visibilitychange',()=>{if(document.hidden){persist();if(playing)stop()}});bindBook();audio.subscribe(syncAudio);audio.setRate(prefs.rate);renderLibrary();
return {
  open:()=>openBook(active.id),
  snapshot:()=>({bookId:'simple:'+active.id,title:active.title,author:active.author,sample:Boolean(active.sample),index,sources:segments().map((s,order)=>({id:`b:${s.ci}:${s.pi}:${s.part}`,kind:'book',title:`Chapter ${s.ci+1} · Passage ${order+1} · ${active.chapters[s.ci].title}`.slice(0,250),text:s.text,order}))}),
  pause:stop,
  resume:play,
  subscribe:listener=>audio.subscribe(()=>listener(active.id,index)),
};

}
